### ISSUE TITLE
Citadel and SubgraphOS are abandonware

### ISSUE THREAD

**Issue by GarlandKey** [subgraph/citadel#14]
Wat do? Should I stop checking back? Do you need funding? Governments intimidating you? Did you just get bored? If you properly open source the code, we might be able to continue where you left off...

**Comment by mckinney-subgraph** [comment]
Citadel is under active development. This repository itself doesn't see a lot of changes -- there are more recent developments under the personal forks of the Subgraph team. But we are also working on a number of other projects outside of this repository that will be included in Citadel. We are not offering/hosting install images at the moment but with some patience Citadel can be built and run in its current state. 

The source code is all available either from Subgraph or team member repos, you just have to browse around a bit.

Citadel is a radical departure from the original version of Subgraph OS (which we call Subgraph OS Classic). Classic is no longer actively developed but all of the source code is up in our repos to the best of my knowledge. 

The ETA on Citadel install images and encouraging the community to try it out is *when we are ready*. Some important things are not finished. We want to get everything right.
